### ISSUE TITLE
set up error

### ISSUE THREAD

**Issue by xcloud2021** [element-plus/element-plus-vite-starter#11]
I git cloned this, and renamed the folder to ui, then:
cd ui
npm install
npm run dev

it come out error:
Failed to resolve entry for package "element-plus". The package may have incorrect main/module/exports specified in its package.json.

ellendeair:ui ellenli$ vue -V
@vue/cli 4.5.10
ellendeair:ui ellenli$ npm -v
6.14.4

any help?

**Comment by chenxch** [comment]
You can use version 1.0.2-beta.33 first. There are problems with version 1.0.2-beta.34.

**Comment by xcloud2021** [comment]
good idea, so how to get 1.0.2-beta.33, branch or tag or ...?

**Comment by chenxch** [comment]
yarn add element-plus@1.0.2-beta.33
I've seen that other issues have solutions to this problem. You can find them

**Comment by YunYouJun** [comment]
I think now it works.
