### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by ngekoding** [element-plus/element-plus-vite-starter#14]
Just run this starter code and make a changes in HelloWord.vue component, but the HMR not working, we must refresh manually. And if we remove the element-plus registration, the HMR works. So, I think the problem comes by Element Plus library.

How can we make Element Plus work with HMR?

node version: v15.11.0
npm version: 7.6.0
element-plus: ^1.0.2-beta.45
vue: ^3.0.5
vite: ^2.3.4

Thanks in advance

**Comment by Iamdyy** [comment]
I met him, too

**Comment by ngekoding** [comment]
Currently I use this way to make HMR works https://github.com/element-plus/element-plus/issues/620#issuecomment-851150714

**Comment by YunYouJun** [comment]
I think it wokrs, try new version?
