### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by kevinzhou1990** [element-plus/element-plus-vite-starter#20]
下载代码后，发现报如下错误
Uncaught SyntaxError: The requested module '/node_modules/.vite/vue.js?v=b456bf5e' does not provide an export named 'createElementBlock'

**Comment by JeremyWuuuuu** [comment]
装一下最新版本的 ElementPlus。因为你用的版本和之前支持的版本不一致所以有这个问题

**Comment by YunYouJun** [comment]
I think it has been resolved. I will close it.
