### ISSUE TITLE
无法使用vue-router

### ISSUE THREAD

**Issue by kiko-love** [element-plus/element-plus-vite-starter#22]
package.json
![image](https://user-images.githubusercontent.com/57704238/133390239-e758d904-f4f6-4af0-9f18-f6fbf99c9eb1.png)
consoleLog
![image](https://user-images.githubusercontent.com/57704238/133390342-4c3a1757-2ab8-4613-9e61-0d313d8fb355.png)
main.ts
![image](https://user-images.githubusercontent.com/57704238/133390400-8d3149c4-9745-4d75-8e25-9b7b2e08fa67.png)
router
![image](https://user-images.githubusercontent.com/57704238/133390444-e1f85888-25fa-4d08-a76e-c2fad1504039.png)

**Comment by YunYouJun** [comment]
You are using vue3, you should install `vue-router@next`. `vue-router@4`

> https://next.router.vuejs.org/
