### ISSUE TITLE
ElMessage not style

### ISSUE THREAD

**Issue by Viin-zx** [element-plus/element-plus-vite-starter#26]
用了unplugin-vue-components 插件我在request.js 中 
import {ElMessage} from 'element-plus'

ElMessage.error() 是没有样式的，这样如何处理

**Comment by YunYouJun** [comment]
You can import this in `src/main.ts`.

```ts
import "element-plus/theme-chalk/src/message.scss"
```

因为 ElMessage 不是一个组件，没有被自动导入。因此你不得不手动导入它。

我在当前仓库，更新了新的示例。
