### ISSUE TITLE
ElMessage, ElMessageBox no style

### ISSUE THREAD

**Issue by Abbylily** [element-plus/element-plus-vite-starter#27]
import {ElMessage, ElMessageBox } from 'element-plus'
export default {
  setup() {
    ElMessage.error('123')
    ElMessageBox.confirm("111", "222", {
      confirmButtonText: "11221",
      cancelButtonText: "123",
    })
      .then(() => {})
      .catch(() => {});
  },
};

ElMessage and ElMessageBox 
![image](https://user-images.githubusercontent.com/21832045/140709952-dad2b778-3a42-4129-9ed2-7c6f9c8e9375.png)

**Comment by MrFu1998** [comment]
`ElMessageBox` 和 `ElMessage` 一样也需要引入样式，但是我引入后发现无遮罩层样式
```
import "element-plus/theme-chalk/src/message.scss"
+ import "element-plus/theme-chalk/src/message-box.scss"
+ import "element-plus/theme-chalk/src/common/popup.scss"
```

**Comment by YunYouJun** [comment]
Yea, we can not use `unplugin-vue-components/vite` to auto import Message style.
Because it is imported by from `element-plus` directly instead of as a component.

Emm, maybe we can find a way to package it into components.

**Comment by Abbylily** [comment]
> `ElMessageBox`和`ElMessage`也需要引入样式，但我添加后发现无遮罩层样式
> 
> ```
> import "element-plus/theme-chalk/src/message.scss"
> + import "element-plus/theme-chalk/src/message-box.scss"
> + import "element-plus/theme-chalk/src/common/popup.scss"
> ```

**Comment by Abbylily** [comment]
> 是的，不能我们使用`unplugin-vue-components/vite`自动导入消息样式。 因为它的英文`element-plus`直接从从导入的，而不是作为组件导入的。
> 
> emmm，也许我们可以想办法把它封装成组件。
> 
> 目前，临时解决方案应由您自己介绍。

除了message 还有其他的组件需要自己引入样式吗？

**Comment by Abbylily** [comment]
> `ElMessageBox` 和 `ElMessage` 一样也需要引入样式，但是我引入后发现无遮罩层样式
> 
> ```
> import "element-plus/theme-chalk/src/message.scss"
> + import "element-plus/theme-chalk/src/message-box.scss"
> + import "element-plus/theme-chalk/src/common/popup.scss"
> ```
> 
> ### update 似乎引入错了文件
> ```
> import "element-plus/theme-chalk/src/message-box.scss"
> import "element-plus/theme-chalk/src/overlay.scss"
> ```
> 
> 这样引入就可以完整实现 `ElMessageBox` 的效果了

还有遇到其他的组件需要单独引入样式吗？

**Comment by YunYouJun** [comment]
If you import something by `import { ElMessage } from 'element-plus'`. You will introduce its style by yourself.
I think that should be well understood.

**Comment by Abbylily** [comment]
> If you import something by `import { ElMessage } from 'element-plus'`. You will introduce its style by yourself. I think that should be well understood.

Ok, I see

**Comment by MrFu1998** [comment]
@YunYouJun  请问 `ElMessageBox`  使用是有什么要求吗，如果引入 `vue-router` 使用会有样式加载问题

代码截图
![vs code 代码图](https://user-images.githubusercontent.com/20925158/141044923-4c4ad384-896c-4ced-b552-63bf1fa18cc9.png)
效果如下
![image](https://user-images.githubusercontent.com/20925158/141044744-b9ac7346-f3e7-4d29-ba0f-5757a8746602.png)

但是我似乎发现如果在 `App.vue` 中使用过 `ElMessageBox`  或者重新引入 `BaseHeader` 组件，则样式恢复了正常
![image](https://user-images.githubusercontent.com/20925158/141045216-85612442-5e60-4f7c-a1d0-e6117784b187.png)

**Comment by YunYouJun** [comment]
@MrFu1998 直接 `import { ElMessageBox} from 'element-plus'` 时，没有自动导入样式，你可以在 `index.scss` 里自行引入 `scss`。例如 `import "element-plus/theme-chalk/src/message-box.scss"`。

**Comment by MrFu1998** [comment]
@YunYouJun 感谢，确实可以了，我看案例是在 `main.ts` 里面引入了 `message` 的样式，一下没想到还可以在 `styles/element/index.scss` 里面引入，如果在 `index.scss` 引入后样式确实不会错乱了

**Comment by shady-xia** [comment]
```scss
@use "element-plus/theme-chalk/src/message-box.scss";
@use "element-plus/theme-chalk/src/overlay.scss";
```

我在 `styles/element/index.scss` 里引了这两个文件，但是现在按钮没有样式，请问还需要引入其他的scss文件吗
![image](https://user-images.githubusercontent.com/20945955/161371448-19568386-65dd-4415-8e43-8d3b7d7bb03a.png)

**Comment by YunYouJun** [comment]
@shady-xia 可能是整个项目没有使用过 button，再引入一下 button？

**Comment by shady-xia** [comment]
> 

应该是当前加载的页面没有使用到button，我在入口文件单独引入了下button的样式就好了，而且我发现还不能在`styles/element/index.scss`里面引button.scss，sass会报循环引用的错。

另外我看了下源码，除了layer，button外，input也可能会出现没被引入的问题

**Comment by YunYouJun** [comment]
你是使用 `@use` 吗？`@use` 应该解决了 `@import` 可能重复的问题。

**Comment by shady-xia** [comment]
> 你是使用 `@use` 吗？`@use` 应该解决了 `@import` 可能重复的问题。

是的，感谢回复，希望能有自动引入ElMessage, ElMessageBox模块样式的功能，现在感觉这种处理方式怪怪的，文档上也没有深入的去说这块的事

**Comment by YunYouJun** [comment]
这方面可能需要专门的逻辑特殊处理，并给 unplugin-vue-components 提 PR。
因为现在的精力在开发 Dark Mode，这方面的工作应该会较迟再做。
如果您有兴趣，可以尝试为其适配。
