### ISSUE TITLE
请问如何使用按需导入

### ISSUE THREAD

**Issue by ruthlessRonin** [element-plus/element-plus-vite-starter#3]
![image](https://user-images.githubusercontent.com/57903721/100609254-a7c06d80-3348-11eb-97c7-a515d1087efc.png)
我安装了babel-plugin-component 但好像不起作用

**Comment by ruthlessRonin** [comment]
全局导入后是需要配置些什么吗，我调用this.$message undefined了

**Comment by ruthlessRonin** [comment]
调用$message解决了 我在vue里多导入了一个getCurrentInstance 然后 const { ctx } = getCurrentInstance() ctx里找到了这个方法

**Comment by zazzaz** [comment]
you can refer to and track on this https://github.com/element-plus/element-plus/issues/719
