### ISSUE TITLE
为什么用的是sass，但是src/styles里面用的是scss

### ISSUE THREAD

**Issue by Renderz** [element-plus/element-plus-vite-starter#31]

**Comment by JeremyWuuuuu** [comment]
I believe this can solve your question: https://stackoverflow.com/questions/5654447/whats-the-difference-between-scss-and-sass

**Comment by YunYouJun** [comment]
简而言之，其实可以把 scss 当作 sass 的一种类 CSS 语法，本质还是 sass。

**Comment by Renderz** [comment]
> 简而言之，其实可以把 scss 当作 sass 的一种类 CSS 语法，本质还是 sass。

谢谢两位大佬答疑解惑。 
因为要是用stylelint，应该还要添加scss和sass两个对应plugin才行。
