### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by helloNN** [element-plus/element-plus-vite-starter#32]
new dependencies found: elemtn-plus/es,element-plus/es/components/menu/style/index, ...., updating...
Failed to write to output file: open C:\Users\nn\Desktop\element-plus-vite-starter\node_modules\.vite\element-plus.js:Access is denied.

**Comment by sxzz** [comment]
Try to run as administrator.

**Comment by helloNN** [comment]
It does't work too.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "element-plus/element-plus-vite-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [element-plus/element-plus-vite-starter] Error (Issue #32)





 
Try to run as administrator.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YunYouJun** [comment]
This is a bug in vite 2.7(Probably). Just delete the node_modules and upgrade vite/element-plus the version.

**Comment by YunYouJun** [comment]
If you still have questions, you can continue to leave a message here. I'll reopen the issue.

**Comment by Godkillme** [comment]
I still have the question as below **with latest vite&element-plus version and other dependencies**.
```
[vite] new dependencies found: @element-plus/icons-vue, updating...
X [ERROR] Failed to write to output file: open C:\Users\ohGod\Documents\eleProject\node_modules\.vite\element-plus.js: Access is denied.
上午11:23:11 [vite] error while updating dependencies:
Error: Build failed with 1 error:
error: Failed to write to output file: open C:\Users\ohGod\Documents\eleProject\node_modules\.vite\element-plus.js: Access is denied.
```

**I have tried all the ways mentioned, such as delete the node_modules, run as administrator, but it does't work at all.**
Please please save the child.

**Comment by YunYouJun** [comment]
Can your provide a minimal example?

**Comment by CalmHarbin** [comment]
I also encountered this problem. How should I solve it in the end

**Comment by YunYouJun** [comment]
In fact, I can't reproduce it.

Does anyone have a minimal example?

**Comment by CalmHarbin** [comment]
You can try this.

https://github.com/CalmHarbin/test

**Comment by YunYouJun** [comment]
> You can try this.
> 
> https://github.com/CalmHarbin/test

In facy, it works well...

<img width="1619" alt="image" src="https://user-images.githubusercontent.com/25154432/159659531-f1d44280-b6eb-46fa-888f-c3dc93e1d29f.png">

I'm in mac. 

Try clearing the node_modules cache.
Or I think this is a permission adaptation problem of vite under windows, not a problem with this template.

**Comment by CalmHarbin** [comment]
thank you, but can you delete my project name from the picture

**Comment by YunYouJun** [comment]
> thank you, but can you delete my project name from the picture

I updated it. 🤣

**Comment by CalmHarbin** [comment]
I upgraded my nodejs version with nvm and successfully solved it.  

nodejs: 14.17.0 -> 16.14.2

https://github.com/nuxt/vite/issues/207

**Comment by helloNN** [comment]
try more until it work.



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 15, 2022 11:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus-vite-starter] Error (Issue #32)




 
I still have the question as below with latest vite&amp;element-plus version and other dependencies.
 [vite] new dependencies found: @element-plus/icons-vue, updating... X [ERROR] Failed to write to output file: open C:\Users\ohGod\Documents\eleProject\node_modules\.vite\element-plus.js: Access is denied. 上午11:23:11 [vite] error while updating dependencies: Error: Build failed with 1 error: error: Failed to write to output file: open C:\Users\ohGod\Documents\eleProject\node_modules\.vite\element-plus.js: Access is denied.  
I have tried all the ways mentioned, such as delete the node_modules, run as administrator, but it does't work at all.
 Please please save the child.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by helloNN** [comment]
Delete node-modules，use npm to install.Try more.



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 22, 2022 14:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus-vite-starter] Error (Issue #32)




 
I also encountered this problem. How should I solve it in the end
