### ISSUE TITLE
启动不起来啊

### ISSUE THREAD

**Issue by zky1347888** [element-plus/element-plus-vite-starter#34]
[plugin:vite:import-analysis] Failed to resolve import "element-plus/theme-chalk/src/message.scss" from "src/main.ts". Does the file exist?

**Comment by YunYouJun** [comment]
Please provide an minimal example.

**Comment by ox01024** [comment]
> [plugin:vite:import-analysis] 无法解析从“src/main.ts”导入“element-plus/theme-chalk/src/message.scss”。文件是否存在？

npm i

**Comment by YunYouJun** [comment]
Just upgrade dependencies & `npm i`/`pnpm i`. I think it has been resolved.
