### ISSUE TITLE
Wrong font on some components

### ISSUE THREAD

**Issue by larserikfinholt** [element-plus/element-plus-vite-starter#35]
Hi! I just cloned the project but have issues with the fonts. Please see fonts higlighted below:

![image](https://user-images.githubusercontent.com/1328417/158774260-5c3f99c2-2270-4cfb-b877-41b38061c008.png)

I would have expected that when I cloned the starter, everything should work out of the box - did I miss some instructions?

I also tried the default "getting started" instructions on the element-plus page, but faced similar issues with the font. Am I missing something?

**Comment by YunYouJun** [comment]
It seems <https://vite-starter.element-plus.org/> works well.
I tried it locally and it also works.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/25154432/158779439-b7bc455a-b53c-4ab1-89f5-1240c3c3f7b3.png">

Are you in `Windows`? Or you set special fonts for your browser?

**Comment by larserikfinholt** [comment]
Yes, I'm in windows.
Here's a screenshot of edge, firefox and chrome

![image](https://user-images.githubusercontent.com/1328417/158800143-5743b8ff-dc44-42c8-a4b5-7871a3423058.png)

No, I've not set any special fonts, default installation. This is how the font settings looks like:

![image](https://user-images.githubusercontent.com/1328417/158800554-e8710fae-f6c8-4306-80c7-76864320d3f4.png)

Anything else I should check?

**Comment by YunYouJun** [comment]
Because `popper`(for datepicker/tooltip) appended in `body`, didn't inherit from `#app`.

So we can add default font-family for `body`, just like https://github.com/element-plus/element-plus-vite-starter/commit/6c532a8a87bca142e2d920d30982e0dacda0a9a9.

Can you check it out and it's working properly now?

**Comment by larserikfinholt** [comment]
Yes, thanks it works now. Thanks!
