### ISSUE TITLE
CommandLine has notice : "This is a bug in the "vite:dep-pre-bundle" plugin."

### ISSUE THREAD

**Issue by dengjiayang** [element-plus/element-plus-vite-starter#37]
✘ [ERROR] [plugin vite:dep-pre-bundle] Detected inconsistent metadata for the path "node_modules/vue/dist/vue.runtime.esm-bundler.js" when it was imported here:

    node_modules/element-plus/es/utils/vue/vnode.mjs:1:103:
      1 │ ...Comment, openBlock, createBlock, createCommentVNode, camelize } from 'vue';
        ╵                                                                         ~~~~~

  The original metadata for that path comes from when it was imported here:

    dep:vue:2:14:
      2 │ export * from "./node_modules/vue/dist/vue.runtime.esm-bundler.js"
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The difference in metadata is displayed below:

   {
  -  "pluginName": null,
  +  "pluginName": "vite:dep-pre-bundle",
   }

  This is a bug in the "vite:dep-pre-bundle" plugin. Plugins provide metadata for a
  given path in an "onResolve" callback. All metadata provided for the same path must be
  consistent to ensure deterministic builds. Due to parallelism, one set of provided
  metadata will be randomly chosen for a given path, so providing inconsistent metadata
  for the same path can cause non-determinism.

**Comment by YunYouJun** [comment]
Can you provide a reproducible example?

**Comment by dengjiayang** [comment]
> 稍晚一些想办法复现一下，在近期的使用中复现率很高，但是看到您的回复后又不复现了，有些蹊跷...

**Comment by YunYouJun** [comment]
I turned it off first, if there is a fully reproducible way, you can turn it back on again.
