### ISSUE TITLE
在组件内使用ElMessageBox样式失效

### ISSUE THREAD

**Issue by AlphaYoung111** [element-plus/element-plus-vite-starter#42]
![image](https://user-images.githubusercontent.com/54132313/173528113-61d91da2-eb6e-4e0f-854e-ee52a407bf2a.png)
模板代码拉下来就加了导入ElMessageBox和使用

**Comment by YunYouJun** [comment]
尝试手动引入 ElMessageBox 样式，因为 ElMessageBox 没有在 Template 中以组件形式存在，所以无法自动导入样式。
