### ISSUE TITLE
emit an empty tooltip.css in dist/assets

### ISSUE THREAD

**Issue by wfk007** [element-plus/element-plus-vite-starter#44]
There is a empty `tooltip.scss` file in `node_modules/element-plus/theme-chalk/src/tooltip.scss`
<img width="494" alt="image" src="https://user-images.githubusercontent.com/22289445/176692887-49ea6420-3a4e-4ce1-85a2-d6d86484516e.png">

when not using the dark theme
<img width="993" alt="image" src="https://user-images.githubusercontent.com/22289445/176693206-8b64ff79-4f14-452e-bbc4-ea4b06456382.png">

it will emit an empty tooltip.css in dist/assets which will throw an error when upload a empty file to CDN

repository to reproduce：https://github.com/wfk007/element-plus-vite-starter

steps:
1. git clone
2. npm install
3. npm run build
4. check the dist/assets folder

**Comment by YunYouJun** [comment]
Empty css file seems works well in jsdelivr.

> `https://cdn.jsdelivr.net/npm/element-plus@2.2.6/theme-chalk/el-tooltip.css`

As you can see, the empty CSS file comes from the empty SCSS file, and for historical reasons, we need to keep it to avoid errors when components automatically import CSS.

If an empty CSS file is bothering you, I suggest you write a `postbuild` script to fix it.

**Comment by wfk007** [comment]
> Empty css file seems works well in jsdelivr.
> 
> > `https://cdn.jsdelivr.net/npm/element-plus@2.2.6/theme-chalk/el-tooltip.css`
> 
> As you can see, the empty CSS file comes from the empty SCSS file, and for historical reasons, we need to keep it to avoid errors when components automatically import CSS.
> 
> If an empty CSS file is bothering you, I suggest you write a `postbuild` script to fix it.

thx reply and suggestions!
I confirmed that the restriction is from the company's server when upload static files to CDN by pipeline
I fixed it by globally import this empty scss file in entry file (main.ts) and force it to build in the global.css
```ts
import "element-plus/theme-chalk/src/tooltip.scss"
```
