### ISSUE TITLE
there is a Unmet peer dependencies error

### ISSUE THREAD

**Issue by basonwoo** [element-plus/element-plus-vite-starter#45]
node: v16.16.0
pnpm: v7.5.2
description: when i run pnpm install, there is a error
```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ vite-ssg
  ├── ✕ missing peer @vueuse/head@"^0.5.0 || ^0.6.0 || ^0.7.0"
  └── ✕ missing peer vue-router@^4.0.1
Peer dependencies that should be installed:
  @vueuse/head@"^0.5.0 || ^0.6.0 || ^0.7.0"  vue-router@^4.0.1
```

i found add `auto-install-peers=true` into `.npmrc` could avoid that

**Comment by YunYouJun** [comment]
It is related with your dependencies & `vite-ssg`.

**Comment by YunYouJun** [comment]
I add `strict-peer-dependencies=false` for this repo to disable this.
