### ISSUE TITLE
暗黑模式下，会生成重复的样式

### ISSUE THREAD

**Issue by hooray** [element-plus/element-plus-vite-starter#46]
![](https://user-images.githubusercontent.com/1574903/184386973-82965cad-4150-4fb3-b475-862cdacaee8b.jpg)

![](https://user-images.githubusercontent.com/1574903/184387046-662e4465-c370-4ac1-801c-6092d5d8f39d.png)

例子就是本仓库在线地址，可以看到在暗黑模式下时，单个 el-button 组件就会生成多个重复的 css ，但在默认模式下是正常的，感觉应该是个 bug

**Comment by YunYouJun** [comment]
I found out why, just move the `dark/css-vars` file out from `styles/element/dark.scss`, because it's reintroduced by `sass.additionalData`.
