### ISSUE TITLE
大佬有试过按需引入吗，我这边按需引入必须全局再引入一次css，不然css不生效

### ISSUE THREAD

**Issue by fellowT** [element-plus/element-plus-vite-starter#5]

**Comment by Zostana** [comment]
项目跑起来嘛？  怎么跑的？？  提示 css引不到，报错

**Comment by fellowT** [comment]
> 项目跑起来嘛？ 怎么跑的？？ 提示 css引不到，报错

不报错，就是css没引入，element组件没css样式

**Comment by zazzaz** [comment]
please try the vite 2 version in the master branch of this project

**Comment by wxxcarl** [comment]
用的就是"vite": "^2.0.0-beta.12"，但是依然没有样式，希望尽快解决，辛苦了

**Comment by wangfpp** [comment]
按需引入是刚需啊  我弄了一下午也没成功
