### ISSUE TITLE
run build 成功，但是頁面上沒有樣式出來，可是在 local dev server 是有效果的

### ISSUE THREAD

**Issue by td231565** [element-plus/element-plus-vite-starter#56]
在 vite.config.ts 加上 css.preprocessorOptions，在 local run dev 可以正常看到 dialog, table 等等，但是 run build 後全部樣式都沒了，請問有哪些設定需要修改呢？

![image](https://github.com/element-plus/element-plus-vite-starter/assets/40486449/0b233320-c4a8-417e-b5d6-7cdd2c06c920)
![image](https://github.com/element-plus/element-plus-vite-starter/assets/40486449/d340f454-cc94-4388-9c70-d3c3f10a3118)

local dev server
<img width="398" alt="image" src="https://github.com/element-plus/element-plus-vite-starter/assets/40486449/fa37a07e-5b48-4fbf-a213-550432db836c">

build production
<img width="189" alt="image" src="https://github.com/element-plus/element-plus-vite-starter/assets/40486449/b5ee1f6a-f7a0-42aa-aa78-5b87287bd896">

**Comment by YunYouJun** [comment]
请提供最小可复现案例。
本仓库的构建 demo 目前是工作的，见 https://vite-starter.element-plus.org/ 。

**Comment by td231565** [comment]
後來直接用 demo 修改，build 後可以正常使用了，謝謝
