### ISSUE TITLE
引入el-switch样式失效

### ISSUE THREAD

**Issue by MaskHao** [element-plus/element-plus-vite-starter#58]
如标题所示，若完整引入没问题

**Comment by MaskHao** [comment]
import { ElSwitch } from 'element-plus'; 再手动导入的情况下
![image](https://github.com/element-plus/element-plus-vite-starter/assets/20870972/ca3004ae-e5b1-44e0-900e-6136c20fd90b)

**Comment by YunYouJun** [comment]
It seems works well. See example https://vite-starter.element-plus.org/
