### ISSUE TITLE
el-date-picker日期组件在使用pnpm安装依赖后，组件无法设置 width: 100%

### ISSUE THREAD

**Issue by tsai996** [element-plus/element-plus-vite-starter#59]
使用pnpm + unplugin-vue-components 会有这个问题！

.ep-date-editor类的**display:inline-block**覆盖了.ep-input的**display:inline-flex**导致的
![Uploading 微信图片_20230730125628.png…]()

**Comment by tsai996** [comment]
![微信图片_20230730125628](https://github.com/element-plus/element-plus-vite-starter/assets/62540486/8589ea3e-36c0-4287-bf9d-5d471f6afe4f)
贴上截图

**Comment by tsai996** [comment]
完整引入 与 npm下载依赖没有这个问题。

**Comment by YunYouJun** [comment]
![image](https://github.com/element-plus/element-plus-vite-starter/assets/25154432/4c0a238d-6283-4844-a547-982105c0d998)
 Seems it had been removed.
