### ISSUE TITLE
项目不会热更新

### ISSUE THREAD

**Issue by agclqq** [element-plus/element-plus-vite-starter#62]
1. 按以下步骤

```
git clone https://github.com/element-plus/element-plus-vite-starter
cd element-plus-vite-starter
npm i
npm run dev
```
提示：
```
  VITE v4.5.0  ready in 6579 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```
2. 修改一个vue中的一个文本，不会热更新。
   如修改`src/components/HelloWorld.vue`的23行，将 `See`改为`seen`，页面不论如何刷新，均看不到`seen`

3. 修改一下vite.config.js，服务器会提示重启
   如加入一空行，再删除此空行，就会提示以下内容，页面也随着刷新，就可以看到`seen`了
```
12:48:24 AM [vite] vite.config.ts changed, restarting server...
12:48:24 AM [vite] server restarted.
```

不知道这是为什么，网上有很多人说是引入组件路径大小写的问题。但此项目刚clone下来，并无修改。
很是抓狂，请帮指点，感谢

**Comment by YunYouJun** [comment]
我 clone 项目，可以正常热更新……


https://github.com/element-plus/element-plus-vite-starter/assets/25154432/8ebaa6a5-f289-4c77-b491-a9194a82bcc1

**Comment by agclqq** [comment]
我又验证了一下，得到以下结论：如果是使用的是windows+wsl，wsl作为node的runtime环境时，代码不要放在windwos目录下。

我用的是windows+wsl，node环境在wsl中，代码放在windows目录下，在wsl中通过/mnt挂载上。这种热更新就失效了。
我又重新在wsl中clone一遍代码，热更新就没问题了。
感谢 @YunYouJun 🙏🤝
