### ISSUE TITLE
按照element-plus官方更换主题色, 没有成功

### ISSUE THREAD

**Issue by myBoringCode** [element-plus/element-plus-vite-starter#64]
按照文档操作 https://element-plus.org/zh-CN/guide/theming.html
![image](https://github.com/element-plus/element-plus-vite-starter/assets/129058082/219e2553-ff09-459d-90fe-dae6f6731ea6)
![image](https://github.com/element-plus/element-plus-vite-starter/assets/129058082/8753a70c-3ad8-4795-909c-21d37fcb53ba)

配置文件都拷贝与https://github.com/element-plus/element-plus-vite-starter 这个库, 但是始终没有生效, 特别是登录页面最明显

**Comment by YunYouJun** [comment]
请提供最小可复现仓库。
