### ISSUE TITLE
ElMessageBox 显示不正常

### ISSUE THREAD

**Issue by gitvzz** [element-plus/element-plus-vite-starter#73]
已在main.js中添加
```
import "element-plus/theme-chalk/src/message-box.scss";
```
当在项目中使用
```
ElMessageBox.alert('显示有问题呀', '提示');
```
或者包括`ElMessageBox.confirm`、`ElMessageBox.prompt` 时，弹出框的顶部显示异常，如图所示：
<img width="504" alt="image" src="https://github.com/user-attachments/assets/ef0fd2cc-904a-4b46-89ae-ce3225265ffe">

**Comment by ykshang** [comment]
我遇到并提交 PR 修复了这个问题，可以查看 [fix: Add message-box‘ s overlay style #85](https://github.com/element-plus/element-plus-vite-starter/pull/85)
