### ISSUE TITLE
按需引入，切换命名空间时，如果我在main.ts使用ElMessage（在App.vue的el-config-provider装载前使用），命名空间不生效

### ISSUE THREAD

**Issue by jiuyuer** [element-plus/element-plus-vite-starter#75]
按需引入，切换命名空间时，如果我在main.ts使用ElMessage（在App.vue的el-config-provider装载前使用），命名空间不生效

**Comment by YunYouJun** [comment]
对于按需引入，你可能需要手动引入变量。

https://github.com/element-plus/element-plus-vite-starter/blob/a3467e7faa255df4a8f3c2719779e5ae2ec3cdeb/src/main.ts#L19

---

对于修改命名空间的情况，你需要配置 `additionalData`： https://github.com/element-plus/element-plus-vite-starter/blob/a3467e7faa255df4a8f3c2719779e5ae2ec3cdeb/vite.config.ts#L19-L26

---

如果仍然未能解决问题，请创建一个最小 Demo。Thanks. https://stackblitz.com/
