### ISSUE TITLE
 As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.

### ISSUE THREAD

**Issue by Ya-hui** [element-plus/element-plus-vite-starter#76]
css跟组件都是按需加载配置成功之后终端会提示这个
 As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.
Recommendation: add `$E: null` at the stylesheet root.

$E: $element !global;

As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.
add `$B: null` at the stylesheet root.
$B: $namespace + $common-separator + $block !global;

我尝试在这段代码上面添加
$E: null;
$B: null;

无效 还是会报错

**Comment by btea** [comment]
It should have been fixed by https://github.com/element-plus/element-plus/pull/18711

**Comment by LiXunGuan** [comment]
> It should have been fixed by [element-plus/element-plus#18711](https://github.com/element-plus/element-plus/pull/18711)

需要等待新版本发布吗？目前2.8.7还是提示这个

**Comment by btea** [comment]
是的。
