### ISSUE TITLE
normalize-wheel does not provide an export named 'default'

### ISSUE THREAD

**Issue by Weeken** [element-plus/element-plus-vite-starter#9]
![image](https://user-images.githubusercontent.com/18238515/103868604-0d500880-5104-11eb-8ff5-1a3bdc876cfa.png)

Uncaught SyntaxError: The requested module '/node_modules/normalize-wheel/index.js?v=1.0.1' does not provide an export named 'default'

**Comment by zazzaz** [comment]
This is because vite does not support UMD bundle. You can config this in your project config.

**Comment by Weeken** [comment]
got it ! thanks.

**Comment by zazzaz** [comment]
Closing this issue since it can only be resolved by Vite, note that Vite is not a very mature tool, use it at your own risk.
